# # backend/src/services/report_service.py
# """
# Report Service
# - Generates report text from scan prediction
# - Creates a real PDF and stores it in static/reports/
# - Saves report document in MongoDB

# Uses:
#   - scans collection for scan data
#   - reports collection to store created report
# """

# from datetime import datetime
# from pathlib import Path
# from typing import Dict, Optional

# from flask import current_app

# from src.extensions import mongo
# from src.db.collections import SCANS, REPORTS


# def _to_objectid(x: str):
#     from bson import ObjectId
#     try:
#         return ObjectId(x)
#     except Exception:
#         return None


# def _public_report(r: dict) -> dict:
#     return {
#         "id": str(r.get("_id")),
#         "scanId": r.get("scanId"),
#         "userId": r.get("userId"),
#         "stage": r.get("stage", ""),
#         "confidence": r.get("confidence", None),
#         "summary": r.get("summary", ""),
#         "createdAt": r.get("createdAt", ""),
#         "pdfUrl": r.get("pdfUrl", ""),
#     }


# def generate_report_for_scan(user_id: str, scan_id: str) -> Dict:
#     """
#     Creates report from scan prediction and writes a PDF.
#     Returns:
#       { reportId, report }
#     """
#     scan = mongo.db[SCANS].find_one({"_id": _to_objectid(scan_id), "userId": user_id})
#     if not scan:
#         raise ValueError("Scan not found")

#     stage = (scan.get("stage") or "").strip() or "UNKNOWN"
#     confidence = scan.get("confidence")

#     summary = build_clinical_summary(stage=stage, confidence=confidence)

#     created_at = datetime.utcnow().isoformat()

#     report_dir = Path(current_app.config["REPORT_DIR"])
#     report_dir.mkdir(parents=True, exist_ok=True)

#     pdf_name = f"report_{scan_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
#     pdf_path = report_dir / pdf_name

#     # Create PDF (simple, dependency-free approach)
#     write_simple_pdf(pdf_path=pdf_path, title="DEMNET MRI Report", body=summary)

#     pdf_url = f"/static/reports/{pdf_name}"

#     doc = {
#         "userId": user_id,
#         "scanId": str(scan_id),
#         "stage": stage,
#         "confidence": confidence,
#         "summary": summary,
#         "pdfUrl": pdf_url,
#         "pdfPath": str(pdf_path),
#         "createdAt": created_at,
#     }

#     ins = mongo.db[REPORTS].insert_one(doc)
#     doc["_id"] = ins.inserted_id

#     return {"reportId": str(ins.inserted_id), "report": _public_report(doc)}


# def build_clinical_summary(stage: str, confidence: Optional[float]) -> str:
#     conf_txt = f"{confidence:.2f}" if isinstance(confidence, (int, float)) else "N/A"

#     # Keep it neutral (not medical advice)
#     return (
#         f"Prediction Summary\n"
#         f"- Predicted Stage: {stage}\n"
#         f"- Model Confidence: {conf_txt}\n\n"
#         f"Notes\n"
#         f"- This output is generated by an AI model for research/assistive use.\n"
#         f"- It is not a medical diagnosis. A qualified clinician must review results.\n\n"
#         f"Recommended Next Steps\n"
#         f"- Verify scan quality and orientation.\n"
#         f"- Correlate with clinical assessments and patient history.\n"
#         f"- Consider follow-up imaging if needed.\n"
#     )


# def write_simple_pdf(pdf_path: Path, title: str, body: str) -> None:
#     """
#     Minimal PDF creation without extra libraries.
#     This produces a basic but valid PDF-like file.

#     If you want a proper PDF layout, tell me "use fpdf"
#     and I will switch to FPDF and update requirements.txt.
#     """
#     # Minimal PDF bytes (basic, not fancy). Works for quick testing.
#     # For production-ready PDFs use fpdf/reportlab.
#     content = f"{title}\n\n{body}\n"
#     pdf_path.write_bytes(content.encode("utf-8"))


from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from src.extensions import mongo
from src.db.collections import REPORTS, SCANS
from src.config import Config


def _to_objectid(x: str):
    from bson import ObjectId
    try:
        return ObjectId(x)
    except Exception:
        return None


def _safe_text(value, fallback=""):
    if value is None:
        return fallback
    return str(value)


def _public_report(doc: dict) -> dict:
    return {
        "id": str(doc.get("_id")),
        "scanId": doc.get("scanId", ""),
        "userId": doc.get("userId", ""),
        "stage": doc.get("stage", ""),
        "confidence": doc.get("confidence", None),
        "summary": doc.get("summary", ""),
        "createdAt": doc.get("createdAt", ""),
        "pdfUrl": doc.get("pdfUrl", ""),
    }


def _build_summary(scan: dict) -> str:
    stage = _safe_text(scan.get("stage"), "Unknown")
    confidence = scan.get("confidence")
    confidence_pct = f"{float(confidence) * 100:.2f}%" if confidence is not None else "N/A"

    return (
        f"This MRI scan was analyzed by the DEMNET-Lite model. "
        f"The predicted stage is {stage} with confidence {confidence_pct}. "
        f"This report is generated for application workflow and demonstration purposes only. "
        f"It should not be treated as a final medical diagnosis."
    )


def _generate_pdf_file(report_doc: dict, scan: dict, pdf_path: Path):
    pdf_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "DEMNET MRI Analysis Report", ln=True)

    pdf.ln(4)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Report ID: {_safe_text(report_doc.get('_id'))}", ln=True)
    pdf.cell(0, 8, f"Scan ID: {_safe_text(report_doc.get('scanId'))}", ln=True)
    pdf.cell(0, 8, f"User ID: {_safe_text(report_doc.get('userId'))}", ln=True)
    pdf.cell(0, 8, f"Created At: {_safe_text(report_doc.get('createdAt'))}", ln=True)

    pdf.ln(4)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Prediction", ln=True)

    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Stage: {_safe_text(report_doc.get('stage'), 'N/A')}", ln=True)

    confidence = report_doc.get("confidence")
    confidence_text = f"{float(confidence) * 100:.2f}%" if confidence is not None else "N/A"
    pdf.cell(0, 8, f"Confidence: {confidence_text}", ln=True)

    probs = report_doc.get("probs") or {}
    if probs:
        pdf.ln(2)
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Class Probabilities", ln=True)

        pdf.set_font("Arial", "", 11)
        for label, value in probs.items():
            try:
                pct = f"{float(value) * 100:.2f}%"
            except Exception:
                pct = "N/A"
            pdf.cell(0, 8, f"{label}: {pct}", ln=True)

    pdf.ln(4)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Summary", ln=True)

    pdf.set_font("Arial", "", 11)
    summary = _safe_text(report_doc.get("summary"), "")
    # fpdf 1.7.2 is safer with latin-1 text
    summary = summary.encode("latin-1", "replace").decode("latin-1")
    pdf.multi_cell(0, 8, summary)

    pdf.ln(4)
    pdf.set_font("Arial", "I", 10)
    note = "For educational and workflow purposes only. Not a substitute for clinical review."
    note = note.encode("latin-1", "replace").decode("latin-1")
    pdf.multi_cell(0, 7, note)

    pdf.output(str(pdf_path))


def generate_report_for_scan(user_id: str, scan_id: str) -> dict:
    oid = _to_objectid(scan_id)
    if not oid:
        raise ValueError("Invalid scan id.")

    scan = mongo.db[SCANS].find_one({"_id": oid, "userId": user_id})
    if not scan:
        raise ValueError("Scan not found.")

    stage = _safe_text(scan.get("stage"), "")
    if not stage:
        raise ValueError("Run inference before generating report.")

    created_at = datetime.utcnow().isoformat()
    summary = _build_summary(scan)

    report_doc = {
        "scanId": str(scan["_id"]),
        "userId": user_id,
        "stage": stage,
        "confidence": scan.get("confidence"),
        "probs": scan.get("probs") or {},
        "summary": summary,
        "createdAt": created_at,
        "pdfPath": "",
        "pdfUrl": "",
    }

    ins = mongo.db[REPORTS].insert_one(report_doc)
    report_doc["_id"] = ins.inserted_id

    pdf_filename = f"report_{str(ins.inserted_id)}.pdf"
    pdf_path = Path(Config.REPORT_DIR) / pdf_filename

    _generate_pdf_file(report_doc, scan, pdf_path)

    pdf_url = f"/api/reports/{str(ins.inserted_id)}/pdf"

    mongo.db[REPORTS].update_one(
        {"_id": ins.inserted_id},
        {
            "$set": {
                "pdfPath": str(pdf_path.resolve()),
                "pdfUrl": pdf_url,
            }
        },
    )

    report_doc["pdfPath"] = str(pdf_path.resolve())
    report_doc["pdfUrl"] = pdf_url

    return {
        "reportId": str(ins.inserted_id),
        "report": _public_report(report_doc),
    }